#### Bài tập tuần 3
##### NUMPY
###### Tạo ma trận random

In [ ]:
import numpy as np

A = np.random.randint(1, 200, (2, 3))
B = np.random.randint(1, 200, (2, 3))
C = np.random.randint(1, 200, (3, 2))
D = np.random.randint(1, 200, (2, 3))

print("\nMa trận A:\n", A)
print("Ma trận B:\n", B)
print("Ma trận C:\n",C)
print("Ma trận D:\n",D)


Ma trận A:
 [[ 27 180 173]
 [ 97 165 107]]
Ma trận B:
 [[ 79 104 164]
 [ 96  82  39]]
Ma trận C:
 [[168 183]
 [186 105]
 [122  80]]
Ma trận D:
 [[185  29 103]
 [ 42 190 152]]


#### 1. Cộng 2 ma trận

In [ ]:
print("Cộng A + B:\n", A + B)

Cộng A + B:
 [[106 284 337]
 [193 247 146]]


#### 2. trừ 2 ma trận

In [ ]:
print("Trừ A - B:\n", A - B)

Trừ A - B:
 [[-52  76   9]
 [  1  83  68]]


#### 3. Nhân từng phần tử của ma trận A với B

In [ ]:
print("Nhân A * B:\n", A * B)

Nhân A * B:
 [[ 2133 18720 28372]
 [ 9312 13530  4173]]


#### 4. Chia 2 ma trận

In [ ]:
print("Chia A / B:\n", A / B)

Chia A / B:
 [[0.34177215 1.73076923 1.05487805]
 [1.01041667 2.01219512 2.74358974]]


#### 5. Nhân 2 ma trận

In [ ]:
print("Nhân C @ D:\n", C @ D)

Nhân C @ D:
 [[38766 39642 45120]
 [38820 25344 35118]
 [25930 18738 24726]]


#### 6. Tích vô hướng của hai vector

In [ ]:
print("Dot product:", np.dot(C, B))

Dot product: [[30840 32478 34689]
 [24774 27954 34599]
 [17318 19248 23128]]


#### 7. Ma trận đơn vị I

In [ ]:
I = np.eye(3)
print("Ma trận đơn vị i 3x3:\n", I)

Ma trận đơn vị i 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 8. Ma trận chuyển vị

In [ ]:
A_reshaped = np.reshape(A, (3, 2))
print("\nMa trận A sau khi thay đổi hình dạng thành 3x2:\n", A_reshaped)


Ma trận A sau khi thay đổi hình dạng thành 3x2:
 [[ 27 180]
 [173  97]
 [165 107]]


#### 9. Nối ma trận

In [ ]:
arr = np.concatenate((A, B), axis=1)
print("\nMa trận A:\n", A)
print("Ma trận B:\n", B)
print("Nối ma trận A và b ta được:", arr)


Ma trận A:
 [[ 27 180 173]
 [ 97 165 107]]
Ma trận B:
 [[ 79 104 164]
 [ 96  82  39]]
Nối ma trận A và b ta được: [[ 27 180 173  79 104 164]
 [ 97 165 107  96  82  39]]


#### 10. Tách ma trận

In [ ]:
E = np.array([2, 5, 8, 9, 20, 999, 1999, 2025])
newE = np.array_split(E,3)
print("\nMa trận E:\n", E)
print("Tách ma trận E thành 3 mảng nhỏ:\n", newE)


Ma trận E:
 [   2    5    8    9   20  999 1999 2025]
Tách ma trận E thành 3 mảng nhỏ:
 [array([2, 5, 8]), array([  9,  20, 999]), array([1999, 2025])]


#### PANDAS
###### 1. Tạo DataFrame từ Dictionary

In [ ]:
import pandas as pd

# Dữ liệu dạng dictionary
data = {
    'Ten': ['Hưng', 'Hội', 'Đăng', 'Quyền'],
    'Tuoi': [21, 16, 20, 22],
    'ThanhPho': ['Vĩnh Long', 'Bình Định', 'Tiền Giang', 'Ngã Ba Chuồng Chó']
}

# Tạo DataFrame
df = pd.DataFrame(data)

print(df)

     Ten  Tuoi           ThanhPho
0   Hưng    21          Vĩnh Long
1    Hội    16          Bình Định
2   Đăng    20         Tiền Giang
3  Quyền    22  Ngã Ba Chuồng Chó


##### 2. Đọc dữ liệu từ file CSV

In [ ]:
import pandas as pd

# Ví dụ đọc từ một URL
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df_titanic = pd.read_csv(url)

# Hiển thị dòng đầu tiên để xem qua dữ liệu
print(df_titanic.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


##### 3. Xem thông tin tổng quan của DataFrame

In [ ]:
# Sử dụng DataFrame từ ví dụ 2
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


##### 4. Lọc dữ liệu theo điều kiện

In [ ]:
# Sử dụng DataFrame từ ví dụ 1
# Lọc ra những người lớn hơn 23 tuổi
df_lon_hon_23 = df[df['Tuoi'] > 23]
print("Người lớn hơn 23 tuổi:")
print(df_lon_hon_23)

# Lọc những người ở Hà Nội VÀ lớn hơn 25 tuổi
df_loc_phuc_tap = df[(df['ThanhPho'] == 'Hà Nội') & (df['Tuoi'] > 25)]
print("\nNgười ở Hà Nội và lớn hơn 25 tuổi:")
print(df_loc_phuc_tap)

Người lớn hơn 23 tuổi:
Empty DataFrame
Columns: [Ten, Tuoi, ThanhPho]
Index: []

Người ở Hà Nội và lớn hơn 25 tuổi:
Empty DataFrame
Columns: [Ten, Tuoi, ThanhPho]
Index: []


##### 5. Thêm một cột mới

In [ ]:
# Sử dụng DataFrame từ ví dụ 1
# Thêm cột 'NamSinh' được tính từ cột 'Tuoi'
nam_hien_tai = 2025
df['NamSinh'] = nam_hien_tai - df['Tuoi']

print(df)

     Ten  Tuoi           ThanhPho  NamSinh
0   Hưng    21          Vĩnh Long     2004
1    Hội    16          Bình Định     2009
2   Đăng    20         Tiền Giang     2005
3  Quyền    22  Ngã Ba Chuồng Chó     2003


6. Xử lý dữ liệu bị thiếu (Missing Data)

In [ ]:
# Sử dụng df_titanic từ ví dụ 2, cột 'Age' có nhiều giá trị thiếu
# Đếm số giá trị thiếu trong mỗi cột
print("Số giá trị thiếu ban đầu:")
print(df_titanic.isnull().sum())

# Cách 1: Xóa các hàng có giá trị thiếu ở cột 'Age'
# df_titanic.dropna(subset=['Age'], inplace=True)

# Cách 2: Điền giá trị trung bình vào các ô bị thiếu của cột 'Age'
gia_tri_trung_binh_tuoi = df_titanic['Age'].mean()
df_titanic['Age'].fillna(gia_tri_trung_binh_tuoi, inplace=True)

print("\nSố giá trị thiếu sau khi điền:")
print(df_titanic.isnull().sum())

Số giá trị thiếu ban đầu:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Số giá trị thiếu sau khi điền:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


/tmp/ipython-input-2795157364.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_titanic['Age'].fillna(gia_tri_trung_binh_tuoi, inplace=True)


7. Nhóm dữ liệu với groupby()

In [ ]:
# Sử dụng df_titanic
# Tính tuổi trung bình của hành khách theo giới tính ('Sex')
tuoi_tb_theo_gioi_tinh = df_titanic.groupby('Sex')['Age'].mean()

print(tuoi_tb_theo_gioi_tinh)

Sex
female    28.216730
male      30.505824
Name: Age, dtype: float64


8. Sắp xếp dữ liệu

In [ ]:
# Sử dụng DataFrame từ ví dụ 1
# Sắp xếp theo tuổi giảm dần
df_sap_xep = df.sort_values(by='Tuoi', ascending=False)

print(df_sap_xep)

     Ten  Tuoi           ThanhPho  NamSinh
3  Quyền    22  Ngã Ba Chuồng Chó     2003
0   Hưng    21          Vĩnh Long     2004
2   Đăng    20         Tiền Giang     2005
1    Hội    16          Bình Định     2009


9. Hợp nhất (Merge) hai DataFrame

In [ ]:
# Tạo 2 DataFrame mẫu
df_info = pd.DataFrame({
    'ID': [1, 2, 3],
    'Ten': ['An', 'Binh', 'Chi']
})

df_diem = pd.DataFrame({
    'ID': [1, 2, 3],
    'DiemToan': [9, 7, 8],
    'DiemVan': [8, 9, 7]
})

# Hợp nhất 2 DataFrame dựa trên cột 'ID'
df_merged = pd.merge(df_info, df_diem, on='ID')

print(df_merged)

   ID   Ten  DiemToan  DiemVan
0   1    An         9        8
1   2  Binh         7        9
2   3   Chi         8        7


10. Áp dụng hàm tùy chỉnh với apply()

In [ ]:
# Sử dụng DataFrame từ ví dụ 1
# Tạo một hàm để phân loại độ tuổi
def phan_loai_tuoi(tuoi):
    if tuoi < 22:
        return 'Trẻ'
    elif 22 <= tuoi <= 28:
        return 'Thanh niên'
    else:
        return 'Trưởng thành'

# Áp dụng hàm này lên cột 'Tuoi' để tạo cột mới 'NhomTuoi'
df['NhomTuoi'] = df['Tuoi'].apply(phan_loai_tuoi)

print(df)

     Ten  Tuoi           ThanhPho  NamSinh    NhomTuoi
0   Hưng    21          Vĩnh Long     2004         Trẻ
1    Hội    16          Bình Định     2009         Trẻ
2   Đăng    20         Tiền Giang     2005         Trẻ
3  Quyền    22  Ngã Ba Chuồng Chó     2003  Thanh niên
