In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Input, Conv1D, Flatten, Dense

# 1. Tạo dữ liệu bảng giả
np.random.seed(42)
n_samples = 20   # số khách hàng
n_features = 4   # số đặc trưng mỗi khách hàng

# Đặc trưng: tuổi, thu nhập, số lần mua trước, số ngày từ lần mua cuối
X = np.random.rand(n_samples, n_features) * 100
y = (X[:,1] + X[:,2] > 100).astype(int)  # quy tắc giả: nếu thu nhập + số lần mua > 100 thì mua

print("=== Dữ liệu đầu vào (X) ===")
print(X)
print("\n=== Nhãn đầu ra (y) ===")
print(y)

# 2. Chuẩn bị dữ liệu cho CNN (reshape thành 3D)
X_cnn = X.reshape((n_samples, n_features, 1))

# 3. Xây dựng mô hình CNN cho tabular data
model = Sequential([
    Input(shape=(n_features, 1)),
    Conv1D(16, kernel_size=2, activation='relu'),
    Flatten(),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 4. Huấn luyện
model.fit(X_cnn, y, epochs=10, verbose=1)

# 5. Dự đoán thử
pred = model.predict(X_cnn[:20])
print("\n=== Dự đoán cho 5 khách hàng đầu tiên ===")
print(pred.round(2))


=== Dữ liệu đầu vào (X) ===
[[37.45401188 95.07143064 73.19939418 59.86584842]
 [15.60186404 15.59945203  5.80836122 86.61761458]
 [60.11150117 70.80725778  2.05844943 96.99098522]
 [83.24426408 21.23391107 18.18249672 18.34045099]
 [30.4242243  52.47564316 43.19450186 29.12291402]
 [61.18528947 13.94938607 29.21446485 36.63618433]
 [45.60699842 78.51759614 19.96737822 51.42344384]
 [59.24145689  4.64504127 60.75448519 17.05241237]
 [ 6.5051593  94.88855373 96.56320331 80.83973481]
 [30.46137692  9.7672114  68.42330265 44.01524937]
 [12.20382348 49.51769101  3.43885211 90.93204021]
 [25.87799816 66.25222844 31.17110761 52.00680212]
 [54.67102793 18.48544555 96.95846278 77.51328234]
 [93.94989416 89.48273504 59.78999788 92.1874235 ]
 [ 8.84925021 19.59828624  4.52272889 32.53303308]
 [38.86772897 27.13490318 82.87375092 35.67533267]
 [28.09345097 54.26960832 14.0924225  80.21969808]
 [ 7.45506437 98.68869366 77.22447693 19.87156815]
 [ 0.55221171 81.54614285 70.68573438 72.9007168 ]
 [7